export const SAVE_REQUEST = "SAVE_REQUEST";
export const SAVE_SUCCESS = "SAVE_SUCCESS";
export const SAVE_FAIL = "SAVE_SUCCESS";

export const GETALL_REQUEST = "GETALL_REQUEST";
export const GETALL_SUCCESS = "GETALL_SUCCESS";
export const GETALL_FAIL = "GETALL_SUCCESS";